"""add_created_by_to_projects_tasks_notes_milestones_attachments

Revision ID: 5ad6a1856f20
Revises: e7156ffbe0c5
Create Date: 2026-07-18 12:52:30.731394

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad6a1856f20'
down_revision: str | None = 'e7156ffbe0c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_checklist_items")
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_attachments_created_by', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_checklist_items_task_id'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_task_id'))

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))
        batch_op.create_foreign_key('fk_milestones_created_by', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_notes_workspace_id'))
        batch_op.create_foreign_key('fk_notes_created_by', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=9),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=40),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_projects_workspace_id'))
        batch_op.create_foreign_key('fk_projects_created_by', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_subtasks_task_id'))

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=9),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('time_spent_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_foreign_key('fk_tasks_created_by', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.alter_column('duration_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_time_entries_started_at'))
        batch_op.drop_index(batch_op.f('ix_time_entries_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'owner'"),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(true)'),
               existing_nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_started_at'), ['started_at'], unique=False)
        batch_op.alter_column('duration_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_created_by', type_='foreignkey')
        batch_op.alter_column('is_pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
        batch_op.alter_column('time_spent_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'medium'"),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'backlog'"),
               existing_nullable=False)
        batch_op.drop_column('created_by')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=9),
               server_default=sa.text("'#3b82f6'"),
               existing_nullable=False)

    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtasks_task_id'), ['task_id'], unique=False)
        batch_op.alter_column('position',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_created_by', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_projects_workspace_id'), ['workspace_id'], unique=False)
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
        batch_op.alter_column('is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'"),
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=40),
               server_default=sa.text("'folder'"),
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=9),
               server_default=sa.text("'#3b82f6'"),
               existing_nullable=False)
        batch_op.drop_column('created_by')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notes_created_by', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_notes_workspace_id'), ['workspace_id'], unique=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               server_default=sa.text("('')"),
               existing_nullable=False)
        batch_op.drop_column('created_by')

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_constraint('fk_milestones_created_by', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)
        batch_op.alter_column('position',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
        batch_op.drop_column('created_by')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_task_id'), ['task_id'], unique=False)
        batch_op.alter_column('position',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attachments_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')

    op.create_table('_alembic_tmp_checklist_items',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('task_id', sa.CHAR(length=32), nullable=False),
    sa.Column('content', sa.VARCHAR(length=500), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=False),
    sa.Column('position', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
